# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Update and minify html,js,css
        run: |
          # sed -i -e "s|COMMIT|${GITHUB_SHA::5}|g" ./index.html
          # sed -i -e "s|main.css|main.min.css|g" ./index.html
          # sed -i -e "s|index.js|index.min.js|g" ./index.html
          npm i
          npm run build
          sed -i -e "s|COMMIT|${GITHUB_SHA::5}|g" ./public/index.html
          rm -rf ./node_modules
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./public"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Send Push
        run: curl -s -F "token=${{ secrets.PUSHOVER_TOKEN }}" -F "user=${{ secrets.PUSHOVER_USER }}" -F "device=iphone_pool" -F "title=memos Deployed Git Pages" -F "message=New version of http://memos.web.app ready" https://api.pushover.net/1/messages
